server:
  port: 8080
  address: 0.0.0.0


# MyBatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cdu.zjy.topictwo.model
  configuration:
    map-underscore-to-camel-case: true


# MySQL?????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/topic_2?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



llm:
  base-url: https://openai.qiniu.com/v1
  api-key: sk-341444a38bf21126dc624193f3f1c8db63dbbce3da2990fcce9a0f5c5bb828c0
  model: deepseek-v3.1

app:
  upload:
    audio-path: D:\Junior\ai-roleplay-project\backend\uploads\audio


asr:
  base-url: https://openai.qiniu.com/v1
  api-key: sk-341444a38bf21126dc624193f3f1c8db63dbbce3da2990fcce9a0f5c5bb828c0
  model: asr

tts:
  base-url: https://openai.qiniu.com/v1
  api-key: sk-341444a38bf21126dc624193f3f1c8db63dbbce3da2990fcce9a0f5c5bb828c0
  model: tts

ngrok:
  url: https://hingeless-servomechanically-janel.ngrok-free.dev

#logging:
##  level:
##    root: info
##    org.mybatis: DEBUG
##    cdu.zjy.topictwo.mapper: DEBUG
#  file:
#    name: logs/topic-two.log
#  pattern:
#    console: "'%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'"
#    file: "'%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'"
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      total-size-cap: 100MB
#      file-name-pattern: logs/topic.%d{yyyy-MM-dd}.log
#      max-history: 30


